---
name: Docker Build and Push
on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yml'
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yml'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DATE: "2025-12-04"
      SUITE: "trixie"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Prepare build variables
        id: prep_vars
        env:
          URL: https://downloads.raspberrypi.com/raspios_lite_${{ matrix.arch }}/images/raspios_lite_${{ matrix.arch }}-${{ env.DATE }}/${{ env.DATE }}-raspios-${{ env.SUITE }}-${{ matrix.arch }}-lite.img.xz
        run: |
          echo "sha256=$(curl -sS "${URL}.sha256" | awk '{print $1}')" >> $GITHUB_OUTPUT
          echo "url=${URL}" >> $GITHUB_OUTPUT
          echo "date=${DATE//-/}" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ startsWith(github.ref, 'refs/tags/') && format('{0}/raspios:{1},{0}/raspios:{1}-{2}', vars.DOCKERHUB_USERNAME, matrix.arch, steps.prep_vars.outputs.date) || format('{0}/raspios:{1}', vars.DOCKERHUB_USERNAME, matrix.arch) }}
          platforms: ${{ matrix.platforms }}
          build-args: |
            RASPIOS_URL=${{ steps.prep_vars.outputs.url }}
            RASPIOS_SHA256=${{ steps.prep_vars.outputs.sha256 }}
    strategy:
      matrix:
        include:
          - arch: arm64
            platforms: linux/arm64
          - arch: armhf
            platforms: linux/arm/v6,linux/arm/v7,linux/arm64
