---
name: Docker Build and Push
on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yml'
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yml'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push:  ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ matrix.tags }}
          platforms: ${{ matrix.platforms }}
          build-args: ${{ matrix.build-args }}
    strategy:
      matrix:
        include:
          - tags: ${{ vars.DOCKERHUB_USERNAME }}/raspios:arm64,${{ vars.DOCKERHUB_USERNAME }}/raspios:arm64-20250513
            platforms: linux/arm64
            build-args: ROOTFS_URL=https://downloads.raspberrypi.com/raspios_lite_arm64/archive/2025-05-13-08:03/root.tar.xz
          - tags: ${{ vars.DOCKERHUB_USERNAME }}/raspios:armhf,${{ vars.DOCKERHUB_USERNAME }}/raspios:armhf-20250513
            platforms: linux/arm/v6,linux/arm/v7,linux/arm64
            build-args: ROOTFS_URL=https://downloads.raspberrypi.com/raspios_lite_armhf/archive/2025-05-13-08:00/root.tar.xz
